// Original passages: three English/Japanese pairs, marker sentence/phrase/kind/explanation, reading lesson.
export const groups = [
['因果・結果・理由', `The warehouse roof was damaged in last night's storm.|昨夜の嵐で倉庫の屋根が損傷しました。|Consequently, today's shipments will leave from our other facility.|その結果、本日の貨物は別の施設から出荷します。|Delivery dates will remain unchanged because additional drivers have been assigned.|運転手を追加配置したため、配達日は変わりません。|2|Consequently|connector|屋根の損傷が出荷場所変更の原因。最後のbecause節は配達日を維持できる理由。|確認：変更されるのは出荷場所。配達日の延期は本文から導けない。
Demand for reusable containers has risen sharply.|再利用可能な容器の需要が急増しています。|As a result, the factory will add a weekend shift.|その結果、工場は週末の勤務帯を追加します。|Current employees may apply for the extra hours before Friday.|現在の従業員は金曜日より前に追加勤務に応募できます。|2|As a result|connector|需要増加→勤務追加→応募案内という展開。結果を示す語で前文と結ぶ。|要旨：増産に必要な人員募集。新工場の建設や全員の義務的勤務は述べていない。
Several guests reported difficulty finding the conference entrance.|複数の参加者が会議場の入口を見つけにくいと報告しました。|For this reason, signs will be placed outside the station.|このため、駅の外に案内標識を設置します。|Volunteers will also guide visitors during the morning registration period.|朝の受付時間にはボランティアも来場者を案内します。|2|For this reason|connector|this reasonは入口が分かりにくいという報告。標識と案内係は同じ問題への対策。|構造：問題→改善策→追加支援。駅そのものが会場だとは断定できない。
Our regular supplier cannot deliver the paper this week.|いつもの仕入先は今週、紙を納品できません。|Therefore, we have placed a smaller order with a local company.|そのため、地元企業に少量の注文をしました。|Please conserve the remaining stock until the delivery arrives.|納品されるまで残りの在庫を節約してください。|2|Therefore|connector|納品不可を受けた代替注文。untilは節約を続ける期間の終点。|行動：在庫を節約する。注文先の変更はすでに実施済み。
The online payment system is undergoing maintenance.|オンライン決済システムは保守作業中です。|Payments cannot be processed until the work is complete.|作業が完了するまで決済を処理できません。|Because the outage was scheduled in advance, no late fees will be charged today.|停止は事前に予定されていたため、本日は延滞料金を請求しません。|3|Because|connector|冒頭の停止状況とは別に、延滞料金を免除する理由を説明する。|確認：今日の延滞料金免除が示される。支払義務そのものの免除ではない。
The cafeteria's new menu has attracted more lunchtime customers.|食堂の新メニューは昼食時の客を増やしました。|This increase has led to longer lines at the cash register.|この増加により、レジの列が長くなっています。|A second register will open next week to shorten waiting times.|待ち時間を短くするため、来週二台目のレジを開設します。|2|This increase|reference|参照先は昼食時の客数の増加。新メニューの品数の増加ではない。|因果の連鎖：新メニュー→客数増→待ち行列→レジ追加。
The inspection revealed that two fire doors would not close properly.|点検で二つの防火扉が正常に閉まらないことが分かりました。|Accordingly, the affected corridor will be closed for repairs.|これを受け、該当する廊下を修理のため閉鎖します。|Employees can reach the offices through the west stairwell.|従業員は西側の階段室から事務室へ行けます。|2|Accordingly|connector|点検結果に基づく措置を示す。最終文は閉鎖に対応する代替経路。|推論：事務室へのアクセスは維持される。建物全体の休業ではない。`],
['対比・譲歩・訂正', `The museum's permanent collection is free to view.|美術館の常設展示は無料で見られます。|However, visitors must purchase a ticket for the special exhibition.|ただし、特別展には入場券の購入が必要です。|Tickets are available online and at the front desk.|入場券はオンラインと受付で販売しています。|2|However|connector|無料の常設展と有料の特別展を対比。後文のTicketsは特別展の券。|確認：無料なのは常設展。美術館の全展示が無料という読みは不可。
The first prototype performed well in laboratory tests.|最初の試作品は実験室の試験で良い性能を示しました。|Nevertheless, the team will conduct field tests before approving production.|それでも、チームは生産を承認する前に実地試験を行います。|These tests will evaluate performance under changing temperatures.|この試験では変動する温度条件下の性能を評価します。|2|Nevertheless|connector|良い結果を認めつつ追加試験が必要だと述べる。逆接は前文の否定とは限らない。|推論：実験室の結果だけでは生産承認に不十分。欠陥が確定したわけではない。
Our basic plan includes telephone support during business hours.|基本プランには営業時間中の電話サポートが含まれます。|In contrast, the premium plan offers assistance around the clock.|対照的に、上位プランは24時間サポートを提供します。|Both plans include automatic software updates.|どちらのプランにもソフトウェアの自動更新が含まれます。|2|In contrast|connector|差異は支援の時間帯。Both以下は対比後に示される共通点。|比較：更新機能でなく、サポート時間でプランを区別する。
The north car park will remain open during construction.|工事中も北側駐車場は利用できます。|Although fewer spaces will be available, monthly pass holders will have priority.|利用できる区画は減りますが、月極パス保有者を優先します。|Other visitors are encouraged to use public transport.|その他の来場者には公共交通機関の利用を勧めます。|2|Although|connector|駐車場継続と収容数減少を区別し、優先利用者という条件も読む。|確認：駐車場の全面閉鎖ではない。一般来場者の駐車禁止とも明記していない。
The workshop was originally scheduled for Tuesday.|講習会は当初、火曜日の予定でした。|Instead, it will be held on Thursday because the instructor is unavailable.|講師の都合がつかないため、代わりに木曜日に開催します。|The location and starting time have not changed.|会場と開始時刻は変わりません。|2|Instead|connector|元の予定を新しい予定で置き換える。変わらない情報も分けて読む。|訂正後の開催日は木曜日。旧予定の火曜日を選ぶ誤りを避ける。
The new desks are more expensive than our current furniture.|新しい机は現在の家具より高価です。|Even so, their adjustable height may reduce employees' discomfort.|それでも、高さを調整できるため従業員の不快感を減らせる可能性があります。|The purchasing team will test two units before placing a larger order.|購買チームは大量注文の前に二台を試用します。|2|Even so|connector|費用の不利を認めた上で利点を示す。mayは効果が確定していないことを表す。|推論：大量購入はまだ決定していない。まず試用して判断する。
The advertisement states that breakfast is included in every booking.|広告には、どの予約にも朝食が含まれると記載されています。|The confirmation email, however, says that the discounted rate excludes meals.|ところが確認メールには、割引料金には食事が含まれないとあります。|Please clarify which information applies to my reservation.|私の予約にはどちらの情報が適用されるかご確認ください。|2|however|connector|広告と確認メールの食事条件が矛盾している。文中のhoweverでも対比を示す。|依頼の目的：条件の確認。食事付き・なしのどちらが正しいかは本文だけでは未確定。`],
['追加・例示・具体化', `The shared office has private meeting rooms.|共同オフィスには個室の会議室があります。|In addition, members can use a secure storage area.|さらに、会員は安全な保管場所を利用できます。|Access to both facilities is included in the monthly fee.|どちらの施設の利用も月額料金に含まれます。|2|In addition|connector|会議室に保管場所という利点を追加。both facilitiesはこの二つを指す。|要旨：月額料金に含まれる設備の紹介。保管場所の追加料金はない。
The new packaging uses less plastic than the old design.|新しい包装は旧デザインよりプラスチックの使用量が少なくなっています。|Moreover, it can be assembled without adhesive.|そのうえ、接着剤なしで組み立てられます。|This simplifies recycling after the product has been unpacked.|これにより、製品を取り出した後のリサイクルが簡単になります。|2|Moreover|connector|材料削減と接着剤不要という二つの利点を追加する。最後のThisは後者の特徴を受ける。|構造：二つの特徴→二つ目の効果。使用量がゼロとは述べていない。
Several departments need additional training.|複数の部署で追加研修が必要です。|For example, the sales team needs practice using the new ordering system.|例えば、営業チームには新しい注文システムを使う練習が必要です。|Department heads should submit their requests by Monday.|部門長は月曜日までに要望を提出してください。|2|For example|connector|営業チームは複数部署の具体例。必要なのが営業だけと限定しない。|行動する人：部門長。研修要望の提出期限は月曜日。
The warranty does not cover damage caused by improper use.|保証は不適切な使用による損傷を対象としません。|For instance, leaving the device outdoors in heavy rain may invalidate the warranty.|例えば、大雨の中で機器を屋外に放置すると保証が無効になる場合があります。|Manufacturing defects are covered for two years.|製造上の欠陥は2年間保証されます。|2|For instance|connector|屋外放置は不適切な使用の例。保証対象外の具体例と対象内の欠陥を分ける。|確認：あらゆる故障を二年間保証するという意味ではない。
The website will display clearer product descriptions.|ウェブサイトに、より分かりやすい製品説明を掲載します。|Specifically, each listing will include dimensions and compatibility information.|具体的には、各掲載ページに寸法と互換性の情報を載せます。|The changes will appear when the site is updated on Saturday.|変更は土曜日のサイト更新時に反映されます。|2|Specifically|connector|抽象的な「分かりやすい説明」を寸法・互換性という内容に具体化。|照合：更新の内容と公開日を別々に抽出する。製品本体の改良ではない。
We offer discounts to registered community groups.|登録済みの地域団体に割引を提供しています。|These include sports clubs and neighborhood associations.|これにはスポーツクラブや町内会が含まれます。|Groups must present proof of registration when booking.|団体は予約時に登録証明を提示する必要があります。|2|These|reference|Theseはcommunity groupsを受ける。例示された二種類だけに限定する表現ではない。|条件：団体の種類だけでなく、登録証明の提示が必要。
The orientation covers essential workplace procedures.|新人説明会では職場の基本手順を扱います。|It also introduces the colleagues who handle payroll and technical support.|また、給与と技術サポートを担当する同僚も紹介します。|Participants will receive a handbook summarizing all the topics.|参加者には全内容をまとめた手引きを配布します。|2|also|connector|手順説明に担当者紹介を追加。Itはorientation、all the topicsは両方の内容を含む。|構造：説明会の内容を列挙→資料配布。給与担当者向けの研修ではない。`],
['条件・例外・適用範囲', `Members receive free delivery on orders of fifty dollars or more.|会員は50ドル以上の注文で配達が無料になります。|This benefit does not apply to express shipments.|この特典は速達便には適用されません。|Express delivery fees are shown at checkout.|速達料金は購入手続き画面に表示されます。|2|does not apply|term|前文の特典を後文で限定。会員・金額条件を満たしても速達は例外。|確認：50ドルちょうどの通常便は対象。速達の無料条件は示されていない。
Applicants may submit a portfolio instead of taking the practical test.|応募者は実技試験の代わりに作品集を提出できます。|Provided that it contains three recent projects, the portfolio will be reviewed.|最近の作品を三点含むことを条件に、作品集を審査します。|Incomplete submissions will be returned without evaluation.|不備のある提出物は評価せず返却します。|2|Provided that|connector|作品集の提出という選択肢に必要な条件を示す。提出だけで合格するわけではない。|条件の照合：最近の作品三点。作品集と実技の両方を義務とはしていない。
The meeting will be held outdoors if the weather permits.|天候が許せば会議を屋外で開催します。|Otherwise, participants should gather in the second-floor lounge.|そうでなければ、参加者は2階のラウンジに集合してください。|An email confirming the venue will be sent that morning.|当日の朝、会場を確定するメールを送ります。|2|Otherwise|connector|屋外で開催できない場合の代替。会場は当日の通知まで条件付き。|推論：現時点で屋外開催は確定していない。雨天での中止とも述べていない。
Visitors may photograph the displays for personal use.|来場者は個人利用のため展示を撮影できます。|However, flash photography is prohibited in the gallery.|ただし、展示室でのフラッシュ撮影は禁止です。|Commercial use of any images requires written permission.|画像の商業利用には書面による許可が必要です。|3|requires written permission|term|個人撮影、フラッシュ、商業利用で異なる規則。条件を一つにまとめない。|適用範囲：フラッシュなしの個人撮影は可。商業利用には別の許可が必要。
Customers can exchange unused items within thirty days.|未使用の商品は30日以内なら交換できます。|Unless the original receipt is presented, only store credit will be offered.|元の領収書を提示しない場合は、店内で使えるクレジットのみ提供します。|Customized products cannot be exchanged.|特注品は交換できません。|2|Unless|connector|領収書のない場合の扱いを示す。最後の特注品という例外は先の条件を満たしても適用。|注意：交換と現金返金は同じではない。本文は現金返金を約束していない。
The shuttle runs every twenty minutes on weekdays.|送迎バスは平日に20分おきに運行します。|On public holidays, service is available only by reservation.|祝日は予約がある場合のみ運行します。|Reservations must be made at least one day in advance.|予約は少なくとも一日前に行う必要があります。|2|only by reservation|term|平日の定期運行に対する祝日の例外。「only」は利用方法を限定する。|確認：祝日の当日予約では条件を満たさない。週末運行は記載されていない。
Employees may work remotely up to two days a week.|従業員は週に二日まで在宅勤務できます。|As long as client meetings are attended in person, managers can approve the arrangement.|顧客との会議に対面出席する限り、管理職はこの勤務形態を承認できます。|Approval must be obtained before the first remote working day.|最初の在宅勤務日の前に承認を得る必要があります。|2|As long as|connector|この文では期間でなく「〜する限り」という条件。対面会議と事前承認を両方確認。|推論：制度があることと各人の自動承認は別。管理職の承認が必要。`],
['時間・順序・予定変更', `The registration desk opens at eight thirty.|受付は8時30分に開きます。|Before entering the hall, participants must collect their name badges.|ホールへ入る前に、参加者は名札を受け取る必要があります。|The opening talk begins at nine.|開会講演は9時に始まります。|2|Before entering the hall|connector|受付→名札受取り→入場→講演の順序。before以下の動作主体はparticipants。|時系列：講演開始時刻と受付開始時刻を取り違えない。
The installation team will arrive on Monday morning.|設置チームは月曜日の朝に到着します。|Once the equipment has been tested, staff will receive training.|機器の試験が終わると、職員は研修を受けます。|Regular operations are expected to resume on Wednesday.|通常業務は水曜日に再開する見込みです。|2|Once|connector|ここでは「いったん〜したら」という時の接続詞。研修は試験完了後。|確度：水曜再開は見込み。設置チームの到着と業務再開は別の段階。
The main entrance will be closed from June first through June tenth.|正面入口は6月1日から6月10日まで閉鎖します。|During this period, visitors should use the entrance on King Street.|この期間中、来場者はキング通り側の入口をご利用ください。|The information desk will remain in its usual location.|案内所は通常の場所で営業を続けます。|2|During this period|reference|this periodは6月1〜10日の閉鎖期間。入口変更を案内所の移転と混同しない。|照合：期間に当たる訪問には代替入口が必要。
We have ordered replacement parts for the elevator.|エレベーターの交換部品を注文しました。|In the meantime, staff should use the stairs near reception.|それまでの間、職員は受付近くの階段を使ってください。|Repairs will begin as soon as the parts arrive.|部品が届き次第、修理を開始します。|2|In the meantime|connector|部品到着を待つ間の暫定措置。到着した時点で修理が完了するわけではない。|順序：注文済み→到着待ち→修理開始。完了日は示されていない。
The bakery previously opened at seven on Saturdays.|パン店は以前、土曜日は7時開店でした。|Starting next month, it will open an hour earlier.|来月からは一時間早く開店します。|Weekday opening hours will remain the same.|平日の開店時刻は変わりません。|2|an hour earlier|term|基準は前文の土曜7時。earlierなので新しい時刻は6時。|計算：来月の土曜日は6時開店。平日の時刻は本文にない。
The software update will be released this evening.|ソフトウェアの更新版は今晩公開します。|After downloading it, users must restart their computers.|ダウンロード後、利用者はコンピューターを再起動する必要があります。|Files should be saved before the restart to prevent data loss.|データ消失を防ぐため、再起動前にファイルを保存してください。|3|before the restart|connector|後から書かれた指示でも、実行順序は保存が再起動より先。|順序：ダウンロード→ファイル保存→再起動。文章の順番と作業順序を区別する。
The supplier promised delivery by the end of last week.|仕入先は先週末までの納品を約束していました。|The goods have not arrived yet, so we have postponed the demonstration.|商品がまだ届いていないため、実演を延期しました。|A new date will be announced after delivery is confirmed.|納品を確認後、新たな日程を知らせます。|2|not arrived yet|term|現在完了の否定で、現在も未着という状態。新日程は納品確認に依存する。|確認：実演は延期。新日程はまだ未確定で、中止とは書かれていない。`],
['指示語・代名詞・参照先', `A digital membership card is now available through our app.|アプリからデジタル会員証を利用できるようになりました。|It can be used instead of the plastic card at all branches.|これは全支店でプラスチックの会員証の代わりに使えます。|Customers who prefer the physical version may continue using it.|実物のカードを希望する顧客は引き続きそれを使えます。|2|It|reference|第2文のItはdigital membership card。第3文末のitはphysical versionで参照先が変わる。|指示語を文ごとに追う。同じitでも常に同じ対象とは限らない。
The purchasing department tested two suppliers' samples.|購買部は二つの仕入先のサンプルを試しました。|The cheaper option was durable, but the other was easier to install.|安い方は丈夫でしたが、もう一方は設置しやすいものでした。|The team chose the latter because installation time was a priority.|設置時間を重視したため、チームは後者を選びました。|3|the latter|reference|二つ目に述べた設置しやすい選択肢。latterは価格の安い方ではない。|選定理由と選ばれた対象を結ぶ。formerなら先に述べた選択肢。
The company will reimburse the course fee and the examination fee.|会社は受講料と試験料を払い戻します。|These expenses must be listed separately on the claim form.|これらの費用は申請書に別々に記載する必要があります。|Receipts for both are required.|両方の領収書が必要です。|2|These expenses|reference|前文の二つの費用をまとめて指す。bothも受講料と試験料の両方。|確認：二つの費用を合計だけで記載するのではなく別記する。
The front gate is being repaired, and delivery trucks cannot enter.|正門は修理中で、配送トラックは入れません。|This has delayed unloading at the warehouse.|このため、倉庫での荷下ろしが遅れています。|Drivers should call reception for directions to the rear gate.|運転手は裏門への道順を受付へ電話で確認してください。|2|This|reference|単独の名詞でなく、門の修理によりトラックが入れないという前文の状況全体。|文章のつながり：進入不可→荷下ろし遅延→代替入口の案内。
Ms. Patel sent a revised agenda to the committee.|パテルさんは改訂した議題を委員会に送りました。|She asked its members to review the budget section before Friday.|彼女は委員に金曜日より前に予算の項目を確認するよう求めました。|Their comments will be discussed at the next meeting.|委員の意見は次の会議で話し合います。|2|its members|reference|itsはcommitteeを指し、SheはMs. Patel。Theirは委員を受ける。|人物・組織を区別：資料の送信者はパテルさん、意見を出すのは委員。
Several employees asked for evening training sessions.|複数の従業員が夜の研修を希望しました。|Those unable to attend during the day can now register for a six o'clock class.|日中に参加できない人は、6時の講座に登録できるようになりました。|The same material will be covered in both sessions.|両方の時間帯で同じ教材を扱います。|2|Those unable to attend during the day|reference|Thoseは日中参加できない従業員を指す。both sessionsは日中と夜の研修。|推論：夜の講座は参加時間の選択肢を増やすもので、別の学習内容ではない。
The supplier sent the invoice and the shipping notice yesterday.|仕入先は昨日、請求書と発送通知を送りました。|The former contains an incorrect tax amount.|前者には誤った税額が記載されています。|Please request a corrected copy before authorizing payment.|支払いを承認する前に訂正版を依頼してください。|2|The former|reference|先に挙げたinvoiceを指す。shipping noticeを訂正する依頼ではない。|順序と対象：請求書訂正→支払い承認。formerとlatterを区別する。`],
['目的・読者・依頼の意図', `Thank you for choosing our conference venue.|当会議施設をお選びいただきありがとうございます。|Please confirm the final number of attendees by Wednesday so that we can arrange seating.|座席を準備できるよう、水曜日までに最終的な参加人数を確認してください。|Your coordinator will send a floor plan the following day.|担当者は翌日に会場図をお送りします。|2|so that we can arrange seating|connector|人数確認を求める目的は座席準備。so thatの後に目的を読む。|読者：会場を予約した顧客。求める行動は人数の確定・連絡。
We noticed that your account has not been used for twelve months.|お客様のアカウントが12か月間使われていないことを確認しました。|To keep it active, please sign in before the end of this month.|利用可能な状態を保つため、今月末までにログインしてください。|No purchase is necessary.|購入は必要ありません。|2|To keep it active|term|ログインの目的はアカウント維持。支払い・購入を求める通知ではない。|行動：期限までのログイン。購入が条件だという推測は最終文と矛盾する。
The safety committee is reviewing our emergency procedures.|安全委員会は緊急時の手順を見直しています。|Employees are invited to report any unclear instructions.|従業員には不明確な指示を報告していただきたいと考えています。|Your feedback will help us revise the handbook before the next drill.|いただいた意見は次の訓練前の手引き改訂に役立ちます。|2|are invited to report|term|invitedはここでは意見提供を呼びかける表現。行事への招待だけではない。|目的：手順の改善のため意見を集める。手引き完成のお知らせではない。
I received the chairs from order number 418 yesterday.|昨日、注文番号418の椅子を受け取りました。|Two of them have scratches on the legs.|うち二脚の脚に傷があります。|Could you arrange replacements without requiring me to return the entire order?|注文分すべてを返送せずに、交換品を手配していただけますか。|3|Could you arrange replacements|term|丁寧な疑問形で交換を依頼する。単に手配能力を尋ねる質問ではない。|意図：傷のある二脚を交換したい。全商品の返品や注文取消しではない。
The city plans to add bicycle parking near the station.|市は駅近くに自転車置き場を増設する予定です。|Residents may review the proposal at the public library.|住民は図書館で計画案を見ることができます。|Comments submitted by May tenth will be considered before the design is finalized.|5月10日までに提出された意見は設計確定前に検討します。|3|before the design is finalized|connector|計画はまだ確定前。意見募集の目的は設計への反映を検討すること。|読者：地域住民。完成施設の利用案内ではなく計画への意見募集。
Our records show that your professional certificate expires next month.|当社の記録では、あなたの専門資格は来月失効します。|Please submit proof of renewal to the personnel office.|更新の証明を人事課へ提出してください。|This will allow us to update your employee file.|これにより従業員の登録情報を更新できます。|3|This|reference|更新証明を提出するという行為を受ける。資格の失効そのものではない。|目的：従業員情報の更新。人事課が資格を自動更新するとは書いていない。
I will be near your office on Thursday afternoon.|木曜日の午後に御社の近くへ行く予定です。|Would it be possible to move our video call to an in-person meeting?|予定しているビデオ通話を対面会議に変更できますか。|The original starting time would still work for me.|元の開始時刻のままで私は構いません。|2|move our video call to an in-person meeting|term|moveはここでは会議形式の変更。開始時刻の変更依頼ではない。|意図：遠隔会議を対面へ。日時変更と読み替えない。`],
['要旨・文章構造・問題解決', `Our customer service team receives many questions about returns.|顧客サービス部には返品について多くの質問が寄せられます。|A new help page now explains the process in three steps.|新しいヘルプページでは手順を三段階で説明しています。|The page also includes a printable return label.|ページには印刷できる返品ラベルもあります。|2|A new help page|term|よくある質問という問題に対する解決策。第三文はその追加機能。|要旨：返品手続きを分かりやすくするページの紹介。返品方針変更とは限らない。
The last employee survey identified noisy work areas as a concern.|前回の従業員調査では、作業場所の騒音が課題に挙がりました。|We have installed sound-absorbing panels in the shared office.|共同オフィスに吸音パネルを設置しました。|A follow-up survey next month will assess whether the change has helped.|来月の追跡調査で、この変更が役立ったか評価します。|3|whether the change has helped|term|対策の効果はまだ評価前。whetherは結果が未確定であることを示す。|構造：問題発見→対策実施→効果確認の予定。改善済みと断定しない。
The branch exceeded its sales target this quarter.|支店は今四半期の売上目標を超えました。|The manager credits the result to improved follow-up with existing customers.|部長は既存顧客へのフォロー改善が成果の理由だとしています。|The same approach will be introduced at two other branches.|同じ方法を他の二支店にも導入します。|2|credits the result to|term|成果の原因を〜に帰する表現。第三文は成功方法の展開。|要旨：成功の報告と横展開。新規顧客だけが売上増の理由ではない。
Our old booking system often displayed rooms that were already occupied.|旧予約システムは使用中の部屋を表示することがよくありました。|The replacement system updates availability immediately after each booking.|新しいシステムは予約のたびに空き状況を即時更新します。|Staff should report any remaining errors to technical support.|職員は残っている不具合を技術サポートへ報告してください。|2|updates availability immediately|term|前文の情報遅延という問題を即時更新で解決する。残る不具合への対処も示す。|構造：旧来の問題→改善内容→利用者への依頼。
The community garden began with only five volunteers.|地域の共同菜園は、わずか五人のボランティアで始まりました。|It now supplies fresh vegetables to three local food banks.|現在は地元の三つの食料支援団体へ新鮮な野菜を供給しています。|The organizers are seeking more volunteers to expand the project.|主催者は活動拡大のため、さらにボランティアを募集しています。|3|to expand the project|term|過去と現在の成長を示した後、今後の拡大に必要な協力を呼びかける。|要旨：活動実績を根拠に参加を募る。野菜販売の広告ではない。
The hotel is renovating its guest rooms one floor at a time.|ホテルは一階ずつ客室を改装しています。|This allows it to remain open throughout the project.|この方法により、工事期間を通じて営業を続けられます。|Work on the final floor is expected to finish in September.|最後の階の工事は9月に終わる見込みです。|2|This|reference|一階ずつ改装するという方法を受け、営業継続の理由を説明する。|要旨：営業を維持する改装計画。9月は新規開業の日ではない。
The revised expense policy takes effect next Monday.|改訂された経費規程は来週月曜日に適用開始します。|Claims must include itemized receipts rather than credit card statements.|申請にはクレジットカード明細ではなく、品目別の領収書が必要です。|An example of an acceptable receipt is attached.|受理できる領収書の例を添付しています。|2|rather than|connector|許容書類と非許容書類を対比して具体的な変更を示す。|構造：適用日→新要件→補助資料。要件を満たす書類の種類を確認する。`],
['推論・含意・発言意図', `The restaurant's website recommends booking at least a week ahead.|レストランのサイトは少なくとも一週間前の予約を勧めています。|When I called today, the earliest available table was next Friday.|今日電話したところ、最も早く取れる席は来週金曜日でした。|We should choose another place for tomorrow's dinner.|明日の夕食には別の店を選んだ方がよさそうです。|2|the earliest available table|term|最短の予約が来週という事実から、明日の予約が取れないと推論できる。|推論の限界：席が埋まっていることは分かるが、評判や料理の品質は断定できない。
The technician arrived without the replacement screen.|技術者は交換用の画面を持たずに来ました。|She said she would return once the part was delivered.|彼女は部品が届いたら再訪すると言いました。|I have borrowed a spare monitor for now.|とりあえず予備のモニターを借りました。|3|for now|term|当面の代替手段を示す。再訪が必要なので、今回修理が完了していないと分かる。|推論：修理待ちで代替機を使用中。部品の納期は不明。
The client asked whether we could send the draft this afternoon.|顧客は今日の午後に草案を送れるか尋ねました。|The editor replied that she had not yet received the photographs.|編集者は写真をまだ受け取っていないと答えました。|She offered to send the text first and add the images tomorrow.|先に文章を送り、明日画像を追加することを提案しました。|2|not yet received the photographs|term|依頼への直接のyes/noでなく、完成版を送れない理由を伝える返答。|意図：写真不足を説明し、段階的な納品を提案する。すべての送付を断るわけではない。
The meeting room has only twelve chairs.|会議室には椅子が十二脚しかありません。|Fifteen people have confirmed attendance.|十五人が出席を確定しています。|Could someone check whether the training room is free?|研修室が空いているか、誰か確認していただけますか。|3|whether the training room is free|term|席数不足から別室を探す意図が分かる。freeはこの文では空いていること。|推論：現会場では席が不足。研修室の利用可否はまだ確認前。
The supplier offered a discount on an order of two hundred units.|仕入先は二百個の注文に割引を提示しました。|Our storage room can hold only one hundred and fifty units.|倉庫には百五十個しか保管できません。|The purchasing manager asked about deliveries in separate batches.|購買部長は分割納品について問い合わせました。|3|deliveries in separate batches|term|注文数量と保管容量の差を埋める解決策。割引が不要だという意味ではない。|意図：保管制約に対応する納品方法の相談。最終注文数はまだ確定していない。
The speaker's flight has been delayed by three hours.|講演者の便が三時間遅れています。|The organizer has moved the panel discussion ahead of the keynote.|主催者は討論会を基調講演より先に移しました。|All sessions will still take place today.|すべてのセッションは本日中に実施します。|2|ahead of the keynote|term|ahead ofはここでは時間的に先。順序変更で到着遅延に対応する。|推論：中止でなく順番を変更した。全セッションが三時間遅れるとは限らない。
The applicant has not worked in retail before.|応募者には小売業で働いた経験がありません。|However, she managed customer accounts at a delivery company for five years.|ただし、配送会社で五年間、顧客の担当をしていました。|The interviewer invited her to describe how she handled complaints.|面接官は苦情への対応方法を説明するよう求めました。|3|how she handled complaints|term|小売の職歴だけでなく、移転可能な顧客対応能力を確認する質問。|推論：関連経験を評価している。採用の決定までは本文にない。`],
['言い換え・文脈語彙', `The software trial lasts fourteen days.|ソフトウェアの試用期間は十四日間です。|Users can explore all features at no cost during this period.|利用者はこの期間、すべての機能を無料で試せます。|Afterward, a paid subscription is required to continue using the program.|その後も使い続けるには有料契約が必要です。|2|at no cost|term|free of chargeと同じく無料の意味。afterwardで無料期間の終了後に条件が変わる。|言い換え：two weeks＝fourteen days。永久無料と読み替えない。
The firm is looking for a temporary assistant.|会社は臨時の事務補助員を募集しています。|The successful candidate will cover for an employee on parental leave.|採用者は育児休業中の従業員の代わりに勤務します。|The assignment is expected to last four months.|勤務期間は四か月の見込みです。|2|cover for|term|人の代わりに仕事を担当する。coverの「覆う」という意味ではない。|言い換え：temporary assignmentは期間限定の仕事。正社員登用は述べていない。
The supplier has discontinued the original battery.|仕入先は従来のバッテリーの販売を終了しました。|A compatible replacement is available through authorized dealers.|対応する代替品は正規販売店で入手できます。|It works with all models sold in the last five years.|それは過去五年間に販売した全機種で使えます。|2|compatible replacement|term|compatibleは既存機器と支障なく使えること。replacementは代替品。|文脈：販売終了は機器全体ではなく旧バッテリー。代替品の対応範囲を確認する。
The committee will consider the proposal at its next meeting.|委員会は次回会議で提案を検討します。|Approval is pending until the cost estimates have been checked.|見積もりを確認するまで承認は保留です。|No equipment should be ordered yet.|まだ機器を注文しないでください。|2|pending|term|ここでは未決・保留中。拒否されたという意味ではない。yetが時点の制限を加える。|言い換え：not yet approved。今後の承認・否認の結果は不明。
The hotel offers a complimentary shuttle from the airport.|ホテルは空港から無料の送迎バスを提供しています。|Seats must be reserved when guests book their rooms.|宿泊客は客室予約時に座席も予約する必要があります。|The service runs between six in the morning and ten at night.|運行時間は朝6時から夜10時までです。|1|complimentary|term|ここでは無料の意味。complementaryは相互補完的という別の語。|照合：無料であっても予約が必要。24時間運行ではない。
The new director will oversee three regional offices.|新任の取締役は三つの地域事務所を統括します。|Each office manager will report directly to her.|各事務所の責任者は彼女に直接報告します。|She will make her first visits next month.|彼女は来月、初めて各事務所を訪問します。|1|oversee|term|superviseに近い「監督・統括する」。見落とすという意味のoverlookと区別する。|言い換え：責任者の報告先＝新任取締役。訪問は来月の予定。
The shipment reached the distribution center this morning.|貨物は今朝、配送センターに到着しました。|It will be dispatched to local stores after inspection.|点検後、地元の店舗へ発送します。|Store managers should expect delivery by Thursday.|店長は木曜日までの納品を見込んでください。|2|dispatched|term|ここではsent out、発送されるという意味。センター到着と店舗への配達は別段階。|言い換え：distribution centerは配送拠点。今朝すでに店舗へ届いたとは読めない。`],
['数値・日付・限定語の照合', `The seminar costs eighty dollars per person.|セミナーは一人80ドルです。|Groups of five or more receive a ten-dollar discount for each participant.|五人以上の団体は参加者一人につき10ドル割引します。|Lunch is included in the fee.|料金には昼食が含まれます。|2|for each participant|term|割引は団体全体で10ドルではなく一人につき10ドル。最低人数にも注意。|計算：五人なら一人70ドル、合計350ドル。昼食代の追加はない。
Orders placed before noon are shipped the same day.|正午より前の注文は当日発送します。|Orders received later are shipped on the next business day.|それ以降の注文は翌営業日に発送します。|The warehouse is closed on weekends.|倉庫は週末休業です。|2|next business day|term|翌暦日でなく次の営業日。発送日と到着日は異なる。|照合：金曜午後の注文は、月曜が営業日なら月曜発送。到着日は未記載。
The express train leaves at nine ten and arrives at ten twenty.|急行は9時10分に出発し、10時20分に到着します。|The local train leaves ten minutes earlier but arrives twenty minutes later.|普通列車は十分早く出発しますが、二十分遅く到着します。|Both stop at Central Station.|どちらも中央駅に停車します。|2|ten minutes earlier|term|比較の基準は急行の時刻。出発9時、到着10時40分と計算する。|計算：急行は70分、普通は100分。共通の停車駅から所要時間を混同しない。
The training room holds a maximum of twenty-four people.|研修室の定員は最大二十四人です。|Eighteen employees have registered, and four guests will join them.|十八人の従業員が登録し、四人の来客が加わります。|The instructor is included in the room's capacity limit.|講師も部屋の定員に含まれます。|3|included in the room's capacity limit|term|参加者だけでなく講師も数える。maximumは上限で、最低人数ではない。|計算：講師一人なら合計23人で、残り一人分。講師の人数条件を明示して判断する。
The membership fee is thirty dollars a month.|会費は月30ドルです。|An annual payment of three hundred dollars is also available.|年払い300ドルも選べます。|Both options provide the same benefits.|どちらの支払い方法でも特典は同じです。|2|annual payment|term|annualは年単位。月払い十二回と比較して費用差を求める。|計算：月払い一年分360ドルに対し年払いは60ドル安い。特典差はない。
The coupon is valid through April thirtieth.|クーポンは4月30日まで有効です。|It applies only to purchases made in the store.|店内での購入にのみ適用します。|Online orders and delivery charges are excluded.|オンライン注文と配達料金は対象外です。|2|only|term|適用範囲を店内購入へ限定。日付条件だけでなく購入方法も満たす必要がある。|照合：期限内のオンライン購入も対象外。throughは最終日を含む表現。
The conference begins on July twelfth.|会議は7月12日に始まります。|Discounted registration closes two weeks before that date.|割引登録はその二週間前に締め切ります。|Regular registration remains open until July tenth.|通常料金の登録は7月10日まで受け付けます。|2|two weeks before that date|term|that dateは7月12日。割引締切と通常締切は別。|計算：二週間前は6月28日。7月10日を割引の締切と読み違えない。`],
['結束性・文挿入・段落の展開', `A new online form will replace the paper application.|新しいオンラインフォームが紙の申込書に代わります。|This change will eliminate the need to mail signed copies.|この変更により、署名した写しを郵送する必要がなくなります。|Applicants will instead confirm their details electronically.|代わりに、応募者は情報を電子的に確認します。|2|This change|reference|前に制度変更の内容が必要。第2文を先頭へ移すと指示語の参照先がなくなる。|文挿入の着眼：This changeという受け手を置く前に、変更内容を提示する。
The firm has introduced flexible working hours.|会社は柔軟な勤務時間制度を導入しました。|Employees may begin work any time between seven and ten.|従業員は7時から10時の間で勤務を開始できます。|However, all staff must be available for meetings at ten thirty.|ただし、全職員は10時30分の会議に参加できる状態でいる必要があります。|3|However|connector|自由な開始時刻の説明の後に、共通の制約を提示する。|展開：制度→具体的な選択幅→例外条件。制約を前に置くと対比の相手が弱くなる。
The exhibition will feature locally produced furniture.|展示会では地元で生産された家具を紹介します。|Visitors can also meet the designers behind the products.|来場者は製品を手がけたデザイナーにも会えます。|They will answer questions during two scheduled sessions.|デザイナーは予定された二回のセッションで質問に答えます。|3|They|reference|直前のdesignersを指す。質問に答える主体がvisitorsだと意味が不自然になる。|文挿入の着眼：人物を導入してから代名詞でその活動を述べる。
The old scanner required staff to enter file names manually.|古いスキャナーでは職員がファイル名を手入力する必要がありました。|The new model creates names automatically from each document's date.|新機種は文書の日付から名前を自動作成します。|As a result, archiving takes less time.|その結果、文書の保管処理にかかる時間が短くなりました。|3|As a result|connector|結果の前に、自動化という原因を示す。oldとnewの比較も一つのまとまり。|展開：旧機種の手間→新機種の機能→効率向上。結果文の位置を根拠付きで判断する。
We are seeking volunteers for the weekend clean-up.|週末の清掃活動のボランティアを募集しています。|Gloves and rubbish bags will be provided.|手袋とごみ袋は主催者が用意します。|Participants should, however, bring their own drinking water.|ただし、参加者は飲料水を各自で持参してください。|3|however|connector|用意される物品に対し、持参が必要な物品を対比。文中の副詞でも関係は同じ。|まとまり：参加準備の二文。飲料水も支給されるという読みを避ける。
The company has selected a site for the new office.|会社は新しい事務所の用地を選びました。|Before construction can begin, the city must approve the plans.|建設開始前に市が計画を承認する必要があります。|Until then, employees will remain at the current location.|それまでは従業員は現在の場所で勤務します。|3|Until then|reference|承認を経て建設開始できる段階までの暫定状況を指す。新事務所完成を意味しない。|展開：決定済み事項→必要な次段階→当面の扱い。用地選定を移転完了としない。
Customers have requested a simpler way to compare products.|顧客から製品をより簡単に比較したいとの要望がありました。|Our website now places key specifications side by side.|当社サイトは主要な仕様を並べて表示するようになりました。|For example, battery life and weight can be compared on one screen.|例えば、電池持続時間と重量を一画面で比較できます。|3|For example|connector|第3文は第2文の機能の具体例。機能説明の後に例を置くと関係が明確。|文挿入の着眼：例示文が説明する一般文を探す。単語の一致だけで位置を選ばない。`],
['関連情報・連絡の照合', `The order confirmation lists delivery to the East Street branch.|注文確認書にはイースト通り支店への配達とあります。|In a later email, the manager asks the supplier to use the new address on Park Road.|その後のメールで、部長は仕入先にパーク通りの新住所を使うよう求めています。|The supplier replies that the address has been updated but the delivery date is unchanged.|仕入先は住所を更新済みで配達日は変わらないと返答しています。|3|has been updated|term|変更依頼だけでなく相手の承諾まで照合する。旧確認書と最新の返答の優先関係を読む。|照合結果：配達先はパーク通り。変更されたのは住所で日付ではない。
The job advertisement requires applicants to submit a resume and two references.|求人広告は履歴書と推薦者二人の提出を求めています。|The applicant's email includes a resume but says that the references will follow tomorrow.|応募者のメールには履歴書があり、推薦者情報は明日送るとあります。|The recruiter will review the application once all documents have arrived.|採用担当者は全書類が届いたら応募を審査します。|3|once all documents have arrived|connector|求人の要件とメールの提出状況を合わせると、まだ審査開始条件を満たしていない。|照合結果：不足は推薦者情報。応募自体の却下が決まったわけではない。
The venue brochure states that the hall seats eighty people.|会場案内にはホールの座席数が八十とあります。|The event organizer's email requests space for ninety guests.|主催者のメールは九十人分のスペースを求めています。|The venue manager offers an adjoining room for the additional guests.|会場責任者は追加の来客用に隣接した部屋を提案しています。|3|additional guests|reference|希望人数90と収容数80の差に当たる来客。additionalは全来客を指さない。|照合：差は10人。隣室の提案が受諾済みとは書かれていない。
The repair estimate excludes transport costs.|修理見積もりには輸送費が含まれていません。|The customer's reply asks whether collection can be included in the quoted price.|顧客の返信は、提示額に集荷を含められるか尋ねています。|The technician agrees to collect the device at no extra charge.|技術者は追加料金なしで機器を集荷することに同意しています。|3|at no extra charge|term|最初の見積条件が後の合意で更新される。collectionは回収・集荷の意味。|照合：合意後は集荷の追加費用なし。すべての輸送費が永久無料とは述べていない。
The invitation asks guests to arrive at six for a reception.|招待状は歓迎会のため6時に到着するよう求めています。|The attached program shows that dinner begins at seven.|添付のプログラムでは夕食開始が7時です。|Guests with dietary requests must notify the organizer by Monday.|食事に関する要望がある方は月曜日までに主催者へ知らせてください。|2|dinner begins at seven|term|招待状の到着時刻とプログラムの食事開始時刻は別。二つの情報は矛盾しない。|照合：6時は受付・歓迎会、7時は夕食。食事要望には別の連絡期限。
The advertisement offers a free upgrade for bookings made in March.|広告は3月中の予約に無料アップグレードを提供しています。|The customer booked in February and traveled in March.|顧客は2月に予約し、3月に旅行しました。|The service agent explains that the promotion is based on the booking date.|担当者はキャンペーンが予約日を基準にすると説明しています。|3|booking date|term|条件の基準は旅行日でなく予約日。広告の条件と顧客の二つの日付を照合する。|結論：この予約は3月予約の条件を満たさない。旅行月だけで判断しない。
The purchase order specifies twenty blue storage boxes.|注文書は青い収納箱二十個を指定しています。|The delivery note lists fifteen blue boxes and five green ones.|納品書には青十五個と緑五個とあります。|The buyer asks for the green boxes to be exchanged rather than for a refund.|購入担当者は返金ではなく、緑の箱の交換を求めています。|3|rather than for a refund|connector|数量の合計は一致するが色が不一致。最後の文で希望する解決方法を限定。|照合：問題は不足ではなく五個の色違い。要求は交換で、返金ではない。`],
['文書の種類・情報の探し方', `Riverside Books is celebrating its tenth anniversary this Saturday.|リバーサイド書店は今週土曜日に十周年を祝います。|Visitors will receive a free bookmark with any purchase.|来店者は購入時に無料のしおりを受け取れます。|The offer is available only while supplies last.|特典は在庫がある間のみ提供します。|3|while supplies last|term|広告の特典に数量上の制限を加える定型表現。期間内でも在庫切れの可能性がある。|文書：販促広告。日時・特典・適用条件を分けて読む。
Guests are requested to keep valuables in the room safe.|宿泊客は貴重品を客室の金庫に保管してください。|Instructions for setting a code are printed inside the safe door.|暗証番号の設定方法は金庫の扉の内側に印刷されています。|If the safe does not open, call the front desk rather than attempting a repair.|金庫が開かない場合は修理を試みず、フロントへ電話してください。|3|rather than attempting a repair|connector|不具合時の許容行動と避ける行動を対比する。|文書：利用案内。通常の操作方法と故障時の連絡先を区別する。
Please find attached the invoice for last month's maintenance service.|先月の保守サービスの請求書を添付します。|Payment is due within fifteen days of the invoice date.|支払期限は請求書の日付から十五日以内です。|Include the invoice number when making a bank transfer.|銀行振込の際は請求書番号を記入してください。|2|of the invoice date|term|十五日の起算点はメール受信日や作業日ではなく請求書の日付。|文書：請求連絡。起算点・期限・振込時の必要情報を抜き出す。
Thank you for completing our customer survey.|顧客アンケートへの回答ありがとうございます。|Most respondents requested later opening hours rather than a wider product range.|回答者の多くは品ぞろえ拡大より営業時間の延長を求めました。|We will test evening opening at two branches next month.|来月、二支店で夜間営業を試行します。|2|Most respondents|term|mostは多数・大部分であって全員ではない。調査結果と次の対応を結び付ける。|文書：調査結果の報告。試行は二支店であり全店導入ではない。
The regional rail operator will introduce a direct airport service in November.|地域の鉄道会社は11月に空港への直通運行を始めます。|The route will remove the need to change trains at Central Station.|この路線では中央駅で乗り換える必要がなくなります。|Ticket prices will be announced after the final timetable is approved.|最終時刻表の承認後に運賃を発表します。|2|remove the need to change trains|term|directという利点を「乗換え不要」と言い換える。運賃の情報はまだ未発表。|文書：ニュース記事。確定した開始予定と未発表の運賃を区別する。
Lena: The client has moved tomorrow's call to two thirty.|レナ：顧客が明日の通話を2時30分に変更しました。|Omar: That overlaps with my training, but I can join for the first fifteen minutes.|オマル：研修と重なりますが、最初の十五分は参加できます。|Lena: I'll put your update first on the agenda.|レナ：議題の最初にあなたの報告を入れます。|3|your update first|reference|yourはOmar、firstは議題順。参加時間の制限に合わせた調整を示す。|文書：チャット。人物・予定衝突・解決策を追う。全員の会議時刻を再変更したわけではない。
To apply for the research assistant position, upload a resume through our website.|研究補助員に応募するには、当方のサイトから履歴書をアップロードしてください。|Applicants should be comfortable preparing spreadsheets and organizing records.|応募者には表計算資料の作成と記録整理に慣れていることを求めます。|Only shortlisted candidates will be contacted for an interview.|選考を通過した候補者にのみ、面接の連絡をします。|3|Only shortlisted candidates|term|onlyで面接連絡の対象を限定。全応募者に返信があるわけではない。|文書：求人案内。応募方法・求める技能・連絡対象を区別する。`],
];
